### ISSUE TITLE
"How To Play" menu is stretched on desktop view

### ISSUE THREAD

**Issue by SethFalco** [josfeldmann/WordGame#1]
If you want to fix it, then that'd be great.
If not, I've been interested in picking up game development for a while now, so I'd be happy to look into Unity and see if I can resolve this in a PR next weekend.

For the most part, it just seems that the "How To Play" section was clearly designed with mobile in mind, so it gets a bit messy on desktop.

![image](https://user-images.githubusercontent.com/22801583/162065757-1befee62-8d13-400a-aa79-b79197ded7c9.png)

**Comment by josfeldmann** [comment]
I think this bug happened after I changed how scaling was handled a few commits back, I just never tested this screen in the editor or on desktop after the change. I pushed a quick fix that should fix the scaling for the most part. There may be edge cases for weird resolutions but it looks fine on my desktop and phone now. I'll update the itch io page this weekend.
